### ISSUE TITLE
Looking into missing files

### ISSUE THREAD

**Issue by jeffboichuk** [GCOM7140/r4ds-exercises#4]
A number of students have noticed that their submissions go missing after they commit them to the [submissions folder](https://github.com/GCOM7140/r4ds-exercises/tree/master/submissions). What's likely to be the cause of these files getting deleted? Can we bring those that have been deleted back?

**Comment by StevenMMortimer** [comment]
@jeffboichuk Can you describe a little more about what "missing" means? Does the file disappear on their machine locally or disappear from the GitHub repo?

**Comment by StevenMMortimer** [comment]
I'm wondering if one possible issue is that students are not frequently "pulling" enough to get everyone's submission, then they commit their submissions folder that doesn't contain the work of others and GitHub considers the files to be deleted from the submission folder since they're not part of the commit that the student makes with their submission.

**Comment by jeffboichuk** [comment]
Sure thing, @StevenMMortimer. The files are disappearing from [the GitHub repo](https://github.com/GCOM7140/r4ds-exercises) (not their machine locally). It might be commits like [this one](https://github.com/GCOM7140/r4ds-exercises/commit/d2c7755bf6121c4d51ace5815e6718a81e13185b) that are doing it. Does that help?

**Comment by StevenMMortimer** [comment]
@jeffboichuk, you are spot on with that commit as an example. Some commits are only one file and they look great, but other commits are changing 10-20 different files. Maybe we can ask someone that had a commit like that if they noticed anything funny when they pushed?
